import { Idea, Category } from "./types";

export const dummyIdeas: Idea[] = [
  {
    id: "1",
    title: "DeFi Lending Pool with Dynamic Interest Rates",
    category: "DeFi",
    preview:
      "A novel approach to DeFi lending that adjusts interest rates based on real-time market volatility and liquidity depth. Uses machine learning to predict optimal rates and automatically rebalances pools to maximize returns for lenders while maintaining competitive rates for borrowers.",
    fullContent:
      "This DeFi lending platform revolutionizes traditional lending by implementing a dynamic interest rate mechanism that responds to market conditions in real-time. The system uses advanced machine learning algorithms to analyze market volatility, liquidity depth, and borrower demand patterns. When volatility increases, rates automatically adjust to protect lenders while still attracting borrowers. The platform features automatic pool rebalancing, ensuring optimal capital allocation across different lending markets. Smart contracts handle all transactions securely, with built-in insurance mechanisms to protect against default risks. The platform also includes a governance token that allows users to vote on protocol parameters and earn rewards for participation.",
    price: 299,
    sellerId: "seller1",
    sellerName: "CryptoBuilder",
    sellerTwitter: "https://twitter.com/cryptobuilder",
    sellerIdeasSold: 12,
    salesCount: 8,
    aiRating: {
      originality: 8.5,
      useCaseValue: 7.2,
      categoryMatch: 9.0,
    },
    createdAt: "2024-11-15",
    status: "live",
  },
  {
    id: "2",
    title: "AI-Powered NFT Curation Marketplace",
    category: "NFTs",
    preview:
      "An intelligent NFT marketplace that uses AI to curate and recommend collections based on user preferences, rarity analysis, and market trends. The platform provides automated valuation and trend prediction to help collectors make informed decisions.",
    fullContent:
      "This innovative NFT marketplace leverages cutting-edge AI technology to transform how collectors discover and evaluate NFTs. The platform uses computer vision to analyze artwork quality, machine learning to predict market trends, and natural language processing to understand community sentiment. Users receive personalized recommendations based on their collection history and preferences. The AI continuously learns from market data to provide accurate valuations and identify undervalued assets. The platform includes social features that allow collectors to form communities around specific artists or collections. Smart contract integration ensures secure transactions with minimal gas fees through layer 2 solutions.",
    price: 199,
    sellerId: "seller2",
    sellerName: "NFTVision",
    sellerTwitter: "https://twitter.com/nftvision",
    sellerIdeasSold: 5,
    salesCount: 3,
    aiRating: {
      originality: 7.8,
      useCaseValue: 8.1,
      categoryMatch: 8.5,
    },
    createdAt: "2024-11-14",
    status: "live",
  },
  {
    id: "3",
    title: "Decentralized Social Network with Token Rewards",
    category: "SocialFi",
    preview:
      "A social media platform where users earn tokens for creating quality content, engaging with posts, and building communities. Content creators can monetize directly through token rewards and NFT-based content ownership.",
    fullContent:
      "This decentralized social network combines the best aspects of traditional social media with Web3 economics. Users earn platform tokens for every meaningful interaction - posting quality content, receiving likes and comments, and building engaged communities. Content creators can mint their posts as NFTs, allowing them to retain ownership and earn royalties when content is shared or referenced. The platform uses a reputation system that rewards authentic engagement while penalizing spam and low-quality content. Governance is community-driven, with token holders voting on platform policies and feature development. The network is built on a scalable blockchain infrastructure that supports millions of users with minimal transaction costs.",
    price: 249,
    sellerId: "seller3",
    sellerName: "SocialChain",
    sellerTwitter: "https://twitter.com/socialchain",
    sellerIdeasSold: 8,
    salesCount: 6,
    aiRating: {
      originality: 8.2,
      useCaseValue: 8.7,
      categoryMatch: 9.2,
    },
    createdAt: "2024-11-13",
    status: "live",
  },
  {
    id: "4",
    title: "Cross-Chain Gaming Asset Marketplace",
    category: "Gaming",
    preview:
      "A unified marketplace for gaming assets across multiple blockchains, allowing players to trade items, characters, and achievements regardless of the game's native chain. Includes interoperability protocols for seamless asset transfers.",
    fullContent:
      "This revolutionary gaming marketplace solves the fragmentation problem in blockchain gaming by creating a unified platform for assets across all major chains. Players can trade items, characters, skins, and achievements from games on Ethereum, Polygon, Solana, and other networks. The platform uses advanced cross-chain bridges and atomic swaps to enable seamless transfers without wrapping or complex conversions. Each asset is verified for authenticity and ownership history is permanently recorded on-chain. The marketplace includes a recommendation engine that suggests similar assets across different games, helping players discover new gaming experiences. Smart contracts handle all transactions with built-in escrow to protect both buyers and sellers.",
    price: 349,
    sellerId: "seller4",
    sellerName: "GameBridge",
    sellerTwitter: "https://twitter.com/gamebridge",
    sellerIdeasSold: 15,
    salesCount: 12,
    aiRating: {
      originality: 9.1,
      useCaseValue: 8.9,
      categoryMatch: 8.8,
    },
    createdAt: "2024-11-12",
    status: "live",
  },
  {
    id: "5",
    title: "DAO Governance Automation Platform",
    category: "DAO",
    preview:
      "An intelligent platform that automates DAO governance processes, including proposal creation, voting mechanisms, and execution. Uses AI to analyze proposals and predict outcomes before voting begins.",
    fullContent:
      "This comprehensive DAO governance platform streamlines the entire decision-making process for decentralized organizations. The platform includes automated proposal templates that help members create well-structured governance proposals. AI analysis provides insights into proposal implications, potential conflicts, and predicted outcomes based on historical voting patterns. The voting system supports multiple mechanisms including quadratic voting, ranked choice, and token-weighted voting. Automated execution ensures that approved proposals are implemented immediately through smart contracts. The platform includes reputation tracking for active members and delegation features that allow token holders to assign voting power to trusted representatives. Analytics dashboards provide transparency into DAO activity and member participation.",
    price: 399,
    sellerId: "seller5",
    sellerName: "DAOFlow",
    sellerTwitter: "https://twitter.com/daoflow",
    sellerIdeasSold: 10,
    salesCount: 7,
    aiRating: {
      originality: 8.0,
      useCaseValue: 9.2,
      categoryMatch: 9.5,
    },
    createdAt: "2024-11-11",
    status: "live",
  },
  {
    id: "6",
    title: "AI Model Marketplace for Developers",
    category: "AI",
    preview:
      "A decentralized marketplace where developers can buy, sell, and license AI models. Includes model versioning, performance metrics, and automated testing to ensure quality before purchase.",
    fullContent:
      "This marketplace revolutionizes how AI models are shared and monetized in the developer community. Developers can upload trained models with detailed documentation, performance metrics, and usage examples. The platform includes automated testing infrastructure that validates models against standard benchmarks before they're listed. Buyers can test models in a sandbox environment before purchasing, ensuring compatibility with their use cases. The marketplace supports various model types including language models, computer vision models, and specialized domain models. Smart contracts handle licensing agreements, with options for one-time purchases, subscriptions, or usage-based pricing. Model creators earn royalties whenever their models are used, creating a sustainable revenue stream.",
    price: 449,
    sellerId: "seller6",
    sellerName: "AIMarket",
    sellerTwitter: "https://twitter.com/aimarket",
    sellerIdeasSold: 6,
    salesCount: 4,
    aiRating: {
      originality: 8.7,
      useCaseValue: 9.0,
      categoryMatch: 9.3,
    },
    createdAt: "2024-11-10",
    status: "live",
  },
  {
    id: "7",
    title: "Decentralized Cloud Storage Network",
    category: "Infrastructure",
    preview:
      "A peer-to-peer cloud storage network that rewards users for sharing unused storage space. Files are encrypted, sharded, and distributed across the network for redundancy and security.",
    fullContent:
      "This decentralized storage network creates a global marketplace for storage capacity, allowing users to monetize unused disk space while providing affordable storage for others. Files are encrypted client-side before upload and then sharded into multiple pieces distributed across different nodes. The system ensures redundancy by storing multiple copies of each shard, guaranteeing data availability even if some nodes go offline. Users earn tokens for providing storage space, with rewards increasing for nodes with better uptime and reliability. The network includes automatic file repair mechanisms that recreate lost shards from redundant copies. Smart contracts handle all storage agreements, with automatic payments and penalties for service level violations.",
    price: 279,
    sellerId: "seller7",
    sellerName: "StorageNet",
    sellerTwitter: "https://twitter.com/storagenet",
    sellerIdeasSold: 9,
    salesCount: 5,
    aiRating: {
      originality: 7.5,
      useCaseValue: 8.3,
      categoryMatch: 8.7,
    },
    createdAt: "2024-11-09",
    status: "live",
  },
  {
    id: "8",
    title: "Yield Farming Aggregator with Risk Scoring",
    category: "DeFi",
    preview:
      "An intelligent aggregator that finds the best yield farming opportunities across DeFi protocols while providing risk scores based on smart contract audits, TVL stability, and historical performance.",
    fullContent:
      "This yield farming aggregator helps users maximize returns while minimizing risks in the DeFi ecosystem. The platform continuously monitors hundreds of DeFi protocols to identify the best yield opportunities. Each opportunity receives a comprehensive risk score based on multiple factors including smart contract audit results, total value locked stability, protocol age, and historical performance during market downturns. Users can set their risk tolerance and receive personalized recommendations. The platform includes automated yield optimization that automatically moves funds between protocols to maximize returns. All interactions are executed through audited smart contracts with built-in slippage protection and emergency withdrawal mechanisms.",
    price: 229,
    sellerId: "seller8",
    sellerName: "YieldMaster",
    sellerTwitter: "https://twitter.com/yieldmaster",
    sellerIdeasSold: 11,
    salesCount: 9,
    aiRating: {
      originality: 7.9,
      useCaseValue: 8.5,
      categoryMatch: 8.9,
    },
    createdAt: "2024-11-08",
    status: "live",
  },
  {
    id: "9",
    title: "Blockchain-Based Supply Chain Verification",
    category: "Infrastructure",
    preview:
      "A transparent supply chain platform that tracks products from origin to consumer using blockchain technology. Ensures authenticity, ethical sourcing, and provides consumers with complete product history.",
    fullContent:
      "This supply chain verification platform brings unprecedented transparency to global commerce by recording every step of a product's journey on the blockchain. Manufacturers, suppliers, and retailers can record product information including origin, certifications, and handling conditions. Consumers can scan QR codes to view complete product history, verifying authenticity and ethical sourcing claims. The platform uses IoT sensors to automatically record environmental conditions during transport, ensuring quality standards are maintained. Smart contracts automate payments between supply chain participants based on verified delivery milestones. The system includes fraud detection algorithms that identify suspicious patterns and flag potential issues for investigation.",
    price: 379,
    sellerId: "seller9",
    sellerName: "ChainVerify",
    sellerTwitter: "https://twitter.com/chainverify",
    sellerIdeasSold: 7,
    salesCount: 4,
    aiRating: {
      originality: 8.3,
      useCaseValue: 9.1,
      categoryMatch: 8.2,
    },
    createdAt: "2024-11-07",
    status: "live",
  },
  {
    id: "10",
    title: "Tokenized Real Estate Investment Platform",
    category: "DeFi",
    preview:
      "A platform that tokenizes real estate properties, allowing fractional ownership and investment in properties worldwide. Includes automated rental distribution and property management features.",
    fullContent:
      "This platform democratizes real estate investment by breaking down properties into tradeable tokens. Investors can purchase fractional ownership in properties across the globe, starting with as little as $100. Each property is represented by an NFT that contains all legal documentation and ownership rights. The platform includes automated rental income distribution, with smart contracts automatically splitting rental payments among token holders based on their ownership percentage. Property management is handled by verified professionals, with all expenses and income transparently recorded on-chain. The platform includes a secondary market where property tokens can be traded, providing liquidity that traditional real estate lacks. Legal compliance is ensured through partnerships with real estate law firms in each jurisdiction.",
    price: 499,
    sellerId: "seller10",
    sellerName: "RealEstateChain",
    sellerTwitter: "https://twitter.com/realestatechain",
    sellerIdeasSold: 4,
    salesCount: 2,
    aiRating: {
      originality: 7.2,
      useCaseValue: 8.8,
      categoryMatch: 7.8,
    },
    createdAt: "2024-11-06",
    status: "live",
  },
  {
    id: "11",
    title: "Decentralized Identity Verification System",
    category: "Infrastructure",
    preview:
      "A self-sovereign identity system that allows users to control their digital identity and selectively share verified credentials. Uses zero-knowledge proofs to verify information without revealing sensitive data.",
    fullContent:
      "This identity verification system puts users in complete control of their digital identity. Users can obtain verified credentials from trusted issuers including governments, educational institutions, and employers. The system uses zero-knowledge proofs to allow users to prove they meet certain criteria without revealing the underlying data. For example, users can prove they're over 21 without revealing their exact age or birthdate. Credentials are stored in a user-controlled wallet and can be revoked by issuers if conditions change. The platform includes a marketplace where service providers can request specific credentials, and users can choose to share them for access. All interactions are encrypted and private, with no central authority having access to user data.",
    price: 329,
    sellerId: "seller11",
    sellerName: "IdentityChain",
    sellerTwitter: "https://twitter.com/identitychain",
    sellerIdeasSold: 13,
    salesCount: 10,
    aiRating: {
      originality: 8.9,
      useCaseValue: 9.3,
      categoryMatch: 8.4,
    },
    createdAt: "2024-11-05",
    status: "live",
  },
  {
    id: "12",
    title: "AI Content Moderation for Web3 Platforms",
    category: "AI",
    preview:
      "An AI-powered content moderation system specifically designed for Web3 platforms. Uses machine learning to detect harmful content while preserving user privacy through on-chain verification.",
    fullContent:
      "This content moderation platform addresses the unique challenges of moderating decentralized platforms where traditional centralized moderation isn't possible. The AI system analyzes content for harmful material including hate speech, scams, and illegal content. Unlike traditional moderation, the system preserves user privacy by processing content locally when possible and using cryptographic proofs to verify moderation decisions. The platform includes a reputation system where moderators earn tokens for accurate moderation, creating incentives for quality work. Appeals processes are handled through decentralized arbitration, with community members voting on disputed cases. The system continuously learns from moderation decisions to improve accuracy while maintaining transparency through on-chain records of all actions.",
    price: 269,
    sellerId: "seller12",
    sellerName: "ModerateAI",
    sellerTwitter: "https://twitter.com/moderateai",
    sellerIdeasSold: 8,
    salesCount: 6,
    aiRating: {
      originality: 8.4,
      useCaseValue: 8.6,
      categoryMatch: 8.8,
    },
    createdAt: "2024-11-04",
    status: "live",
  },
  {
    id: "13",
    title: "Cross-Chain DEX Aggregator",
    category: "DeFi",
    preview:
      "A decentralized exchange aggregator that finds the best swap rates across multiple chains and DEXs. Executes trades atomically across chains when beneficial, saving users time and money.",
    fullContent:
      "This DEX aggregator revolutionizes cross-chain trading by intelligently routing trades across multiple blockchains and decentralized exchanges to find the best rates. The platform analyzes liquidity across Ethereum, Polygon, Arbitrum, Optimism, and other networks to determine optimal swap paths. When beneficial, the system can split a single trade across multiple DEXs on the same chain or execute atomic swaps across different chains. Users simply specify their input and output tokens, and the platform handles all complexity including bridge selection, slippage protection, and gas optimization. The platform includes a gas price oracle that predicts optimal transaction timing to minimize costs. All trades are executed through audited smart contracts with built-in MEV protection.",
    price: 319,
    sellerId: "seller13",
    sellerName: "SwapMaster",
    sellerTwitter: "https://twitter.com/swapmaster",
    sellerIdeasSold: 14,
    salesCount: 11,
    aiRating: {
      originality: 7.7,
      useCaseValue: 9.4,
      categoryMatch: 9.1,
    },
    createdAt: "2024-11-03",
    status: "live",
  },
  {
    id: "14",
    title: "NFT Royalty Enforcement Protocol",
    category: "NFTs",
    preview:
      "A protocol that ensures NFT creators receive royalties on secondary sales across all marketplaces. Uses smart contracts and marketplace integrations to automatically enforce royalty payments.",
    fullContent:
      "This protocol solves the royalty enforcement problem in the NFT ecosystem by creating a universal system that ensures creators are paid on every secondary sale. The protocol includes a registry where creators can register their NFTs with desired royalty rates. Marketplaces that integrate with the protocol automatically enforce these royalties through smart contracts. The system uses on-chain verification to ensure that even marketplaces that don't natively support royalties still pay creators through automated mechanisms. Creators can update royalty rates for future sales while respecting existing sales agreements. The protocol includes analytics that track royalty payments across all marketplaces, providing transparency for creators. Dispute resolution mechanisms handle edge cases and ensure fair enforcement.",
    price: 189,
    sellerId: "seller14",
    sellerName: "RoyaltyGuard",
    sellerTwitter: "https://twitter.com/royaltyguard",
    sellerIdeasSold: 6,
    salesCount: 3,
    aiRating: {
      originality: 8.6,
      useCaseValue: 8.2,
      categoryMatch: 9.0,
    },
    createdAt: "2024-11-02",
    status: "live",
  },
  {
    id: "15",
    title: "Decentralized Prediction Market Platform",
    category: "Other",
    preview:
      "A prediction market where users can bet on real-world events and earn rewards for accurate predictions. Uses oracle networks for reliable event resolution and includes governance features for disputed outcomes.",
    fullContent:
      "This prediction market platform allows users to create and participate in markets for any real-world event. Users can bet on outcomes ranging from sports results to election outcomes to weather predictions. The platform uses multiple oracle networks to ensure reliable and unbiased event resolution. Market creators set initial odds and can earn fees from trading activity. The platform includes sophisticated mechanisms to prevent manipulation, including stake limits and reputation systems. Disputed outcomes are resolved through community governance, with token holders voting on the correct result. The platform includes analytics that track prediction accuracy over time, helping users identify the most reliable predictors. All markets are fully transparent with on-chain records of all bets and outcomes.",
    price: 289,
    sellerId: "seller15",
    sellerName: "PredictChain",
    sellerTwitter: "https://twitter.com/predictchain",
    sellerIdeasSold: 9,
    salesCount: 7,
    aiRating: {
      originality: 7.8,
      useCaseValue: 8.4,
      categoryMatch: 7.5,
    },
    createdAt: "2024-11-01",
    status: "live",
  },
  {
    id: "16",
    title: "Automated Portfolio Rebalancing for Crypto",
    category: "DeFi",
    preview:
      "An intelligent portfolio management system that automatically rebalances crypto holdings based on user-defined strategies, market conditions, and risk tolerance. Includes tax optimization features.",
    fullContent:
      "This portfolio management platform automates the complex task of maintaining optimal asset allocation in crypto portfolios. Users can choose from pre-built strategies like market cap weighting, risk parity, or momentum-based allocation, or create custom strategies. The system continuously monitors market conditions and automatically rebalances portfolios when allocations drift from targets. Advanced features include tax-loss harvesting that strategically realizes losses to offset gains, minimizing tax liability. The platform integrates with major exchanges and DeFi protocols to execute rebalancing trades efficiently. Risk management features include automatic position sizing based on volatility and correlation analysis to prevent over-concentration. All trades are executed through secure smart contracts with user-defined limits and safeguards.",
    price: 239,
    sellerId: "seller16",
    sellerName: "PortfolioAI",
    sellerTwitter: "https://twitter.com/portfolioai",
    sellerIdeasSold: 12,
    salesCount: 8,
    aiRating: {
      originality: 7.3,
      useCaseValue: 8.7,
      categoryMatch: 8.3,
    },
    createdAt: "2024-10-31",
    status: "live",
  },
  {
    id: "17",
    title: "Blockchain-Based Academic Credential Verification",
    category: "Infrastructure",
    preview:
      "A platform where educational institutions can issue verifiable credentials on the blockchain. Employers can instantly verify degrees and certifications without contacting institutions directly.",
    fullContent:
      "This platform transforms how academic credentials are issued and verified by moving the process to the blockchain. Educational institutions can issue degrees, certificates, and transcripts as verifiable credentials that are permanently recorded on-chain. Employers can verify credentials instantly by checking the blockchain, eliminating the need for time-consuming verification processes. The system includes privacy features that allow students to share specific credentials without revealing their entire academic history. Credentials can include detailed information like course grades, GPA, and honors, all cryptographically verified. The platform includes a marketplace where students can selectively share credentials with employers, maintaining control over their academic data. Integration with existing student information systems makes adoption seamless for institutions.",
    price: 359,
    sellerId: "seller17",
    sellerName: "EduChain",
    sellerTwitter: "https://twitter.com/educhain",
    sellerIdeasSold: 5,
    salesCount: 3,
    aiRating: {
      originality: 8.1,
      useCaseValue: 9.0,
      categoryMatch: 8.6,
    },
    createdAt: "2024-10-30",
    status: "live",
  },
  {
    id: "18",
    title: "Decentralized Music Streaming with Artist Ownership",
    category: "Other",
    preview:
      "A music streaming platform where artists retain ownership of their music and earn directly from streams. Uses blockchain to track plays and distribute royalties automatically to all rights holders.",
    fullContent:
      "This music streaming platform disrupts the traditional music industry by giving artists complete control and ownership of their work. Artists upload music directly to the platform and set their own streaming prices. Every play is recorded on the blockchain, ensuring transparent and accurate royalty distribution. Smart contracts automatically split royalties among artists, producers, and other rights holders based on pre-defined agreements. Listeners can support artists directly through tips and NFT purchases of exclusive content. The platform includes social features that help artists build communities and engage with fans. Unlike traditional streaming services, artists receive the majority of streaming revenue, with only minimal platform fees. The platform uses decentralized storage to ensure music is always available and resistant to censorship.",
    price: 269,
    sellerId: "seller18",
    sellerName: "MusicChain",
    sellerTwitter: "https://twitter.com/musicchain",
    sellerIdeasSold: 7,
    salesCount: 5,
    aiRating: {
      originality: 8.5,
      useCaseValue: 8.9,
      categoryMatch: 7.9,
    },
    createdAt: "2024-10-29",
    status: "live",
  },
];

export const categories: Category[] = [
  "DeFi",
  "AI",
  "SocialFi",
  "DAO",
  "Gaming",
  "NFTs",
  "Infrastructure",
  "Other",
];

export const stats = {
  totalIdeas: 18,
  totalSales: 127,
  activeSellers: 18,
};
